CREATE TABLE `eda_colabs` (
  `id` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_eda` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_colaborador` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_evaluacion` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_evaluacion_2` char(36) COLLATE utf8mb4_unicode_ci NOT NULL,
  `id_cuestionario_colab` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_cuestionario_super` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_feedback_1` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_feedback_2` char(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `enviado` tinyint(1) NOT NULL DEFAULT '0',
  `aprobado` tinyint(1) NOT NULL DEFAULT '0',
  `cerrado` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_envio` timestamp NULL DEFAULT NULL,
  `fecha_aprobado` timestamp NULL DEFAULT NULL,
  `fecha_cerrado` timestamp NULL DEFAULT NULL,
  `promedio` int NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `eda_colabs_id_evaluacion_index` (`id_evaluacion`),
  KEY `eda_colabs_id_evaluacion_2_index` (`id_evaluacion_2`),
  KEY `eda_colabs_id_cuestionario_colab_index` (`id_cuestionario_colab`),
  KEY `eda_colabs_id_cuestionario_super_index` (`id_cuestionario_super`),
  KEY `eda_colabs_id_feedback_1_index` (`id_feedback_1`),
  KEY `eda_colabs_id_feedback_2_index` (`id_feedback_2`),
  CONSTRAINT `eda_colabs_id_cuestionario_colab_foreign` FOREIGN KEY (`id_cuestionario_colab`) REFERENCES `cuestionarios` (`id`),
  CONSTRAINT `eda_colabs_id_cuestionario_super_foreign` FOREIGN KEY (`id_cuestionario_super`) REFERENCES `cuestionarios` (`id`),
  CONSTRAINT `eda_colabs_id_evaluacion_2_foreign` FOREIGN KEY (`id_evaluacion_2`) REFERENCES `evaluaciones` (`id`),
  CONSTRAINT `eda_colabs_id_evaluacion_foreign` FOREIGN KEY (`id_evaluacion`) REFERENCES `evaluaciones` (`id`),
  CONSTRAINT `eda_colabs_id_feedback_1_foreign` FOREIGN KEY (`id_feedback_1`) REFERENCES `feedbacks` (`id`),
  CONSTRAINT `eda_colabs_id_feedback_2_foreign` FOREIGN KEY (`id_feedback_2`) REFERENCES `feedbacks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;